version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    container_name: postgres-container-attempt5
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    volumes:
      - postgres-container-attempt5:/var/lib/postgresql/data

volumes:
  postgres-container-attempt5: